### PR TITLE
Refactor docs

### PR DESCRIPTION
**Pull request by erip**
This PR unifies the docs and adds extensions for automatic rendering in GitHub.

### CODE REVIEW

**Comment by kylebgorman** [comment]
I'm not sure if this matters anymore (maybe this should just work on GitHub and that's fine) but I think I went with .rst only because PyPi only supports it (and not Markdown). Does anybody care about the docs being rendered in HTML on PyPi?

**Comment by erip** [comment]
Ah, yes. FWIW, the conversion is simple enough, but perhaps needless. I can make the README an rst instead since GitHub can render either.

**Comment by kylebgorman** [comment]
Yeah, let's do that instead!

One last small request: for context, can you rewrite the sentence from the
old README.md to read something like:

"Note that the GitHub repository is a (primarily read-only) mirror to
enable bug reports and outside contributions."

**Comment by erip** [comment]
It's [here](https://github.com/kylebgorman/Pynini/pull/2/commits/18a3bc19f34c4cdf8305183b371d445eb07aac97#diff-88b99bb28683bd5b7e3a204826ead112R18).

**Comment by erip** [comment]
Eep, don't merge yet... rst isn't rendering quite correctly...

**Comment by erip** [comment]
OK, at last... I've made the changes so rst can render. What a silly markup. :-)

**Pull request merged**
